### ISSUE TITLE
WP Plugins

### ISSUE THREAD

**Issue by edimitchel** [YsarocK/nuxt-wp#1]
Just creating this issue to share my issue I got when I tried to use Nuxt with Wordpress.

Working with plugins from Wordpress is not an easy thing to bring it into Nuxt frontend stuff.

I'm wondering about simplifying usage of them in a way that plugins could be used as wordpress does with short code (`[code]`) but transposed as Nuxt/Vue components ?

**Comment by YsarocK** [comment]
Thanks for the issue.
The idea is not to make the package that polyvalent, or I could think switching to a layer instead. It would ask a lot of work.
However, I have in mind to make it quite "complete" by bringing the ability to display/submit CF7 forms.
